package com.tx.txspringboot.controller;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.servlet.ModelAndView;

/**
 * Created by IntelliJ IDEA.
 *
 * @author Eric
 * @since 2018/3/8 17:14
 */
@Controller
@RequestMapping("/")
public class HomeController {
    private static Logger logger = LogManager.getLogger();

    @RequestMapping(value = {"", "index", "home"}, method = RequestMethod.GET)
    public ModelAndView home() {
        logger.info(BANNER_BIG);

        ModelAndView view = new ModelAndView("home");
        view.addObject("banner", BANNER_DEFAULT);
        return view;
    }

    // generated by http://www.network-science.de/ascii/
    private static final String BANNER_DEFAULT =
            " __      __       .__                             ._.\n" +
                    "/  \\    /  \\ ____ |  |   ____  ____   _____   ____| |\n" +
                    "\\   \\/\\/   // __ \\|  | _/ ___\\/  _ \\ /     \\_/ __ \\ |\n" +
                    " \\        /\\  ___/|  |_\\  \\__(  <_> )  Y Y  \\  ___/\\|\n" +
                    "  \\__/\\  /  \\___  >____/\\___  >____/|__|_|  /\\___  >_\n" +
                    "       \\/       \\/          \\/            \\/     \\/\\/\n" +
                    "\n";

    private static final String BANNER_BIG =
            "__          __  _                          _ \n" +
                    "\\ \\        / / | |                        | |\n" +
                    " \\ \\  /\\  / /__| | ___ ___  _ __ ___   ___| |\n" +
                    "  \\ \\/  \\/ / _ \\ |/ __/ _ \\| '_ ` _ \\ / _ \\ |\n" +
                    "   \\  /\\  /  __/ | (_| (_) | | | | | |  __/_|\n" +
                    "    \\/  \\/ \\___|_|\\___\\___/|_| |_| |_|\\___(_)\n" +
                    "\n";
}
